include: package:lints/recommended.yaml

linter:
  rules:
    # Style rules
    - camel_case_types
    - camel_case_extensions
    - library_names
    - file_names
    - non_constant_identifier_names
    - constant_identifier_names
    - directives_ordering
    - lines_longer_than_80_chars
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - avoid_unnecessary_containers
    - use_key_in_widget_constructors
    
    # Documentation rules
    - public_member_api_docs
    
    # Error prevention rules
    - prefer_is_empty
    - prefer_is_not_empty
    - avoid_print
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_typing_uninitialized_variables
    - use_build_context_synchronously

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
