name: flutter_cep2
description: A Brazilian ZIP code (CEP) lookup library for Dart and Flutter applications. Supports multiple output formats including JSON and XML.
version: 1.0.2
homepage: https://github.com/vitoramaral10/flutter_cep2
repository: https://github.com/vitoramaral10/flutter_cep2
issue_tracker: https://github.com/vitoramaral10/flutter_cep2/issues
documentation: https://github.com/vitoramaral10/flutter_cep2#readme
funding: https://github.com/sponsors/vitoramaral10

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  http: ^1.2.0
  xml2json: ^6.2.7
  meta: ^1.12.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.9

topics:
  - cep
  - brazil
  - address
  - postal-code
  - viacep

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
