name: flutter_cep2
description: Uma biblioteca para consulta de CEP para desenvolvedores Dart
  (Console, Web e Flutter).
version: 0.0.13
homepage: https://viacep.com.br/
repository: https://github.com/vitoramaral10/flutter_cep2
issue_tracker: https://github.com/vitoramaral10/flutter_cep2/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  
  http: ^0.13.5
  xml2json: ^5.3.5

dev_dependencies:
  dart_code_metrics: ^4.18.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
