name: flutter_cep2
description: Uma biblioteca para consulta de CEP para desenvolvedores Dart
  (Console, Web e Flutter).
version: 0.0.8
homepage: https://viacep.com.br/
repository: https://github.com/vitoramaral10/flutter_cep2
issue_tracker: https://github.com/vitoramaral10/flutter_cep2/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.4
  xml2json: ^5.3.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
